/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicTimersRouteImport } from './routes/(public)/timers'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as authenticatedDashboardWeddingEventIdIndexRouteImport } from './routes/(authenticated)/dashboard/$weddingEventId/index'
import { Route as authenticatedDashboardTimersTimerIdRouteRouteImport } from './routes/(authenticated)/dashboard/timers/$timerId/route'
import { Route as authenticatedDashboardTimersTimerIdEditRouteImport } from './routes/(authenticated)/dashboard/timers/$timerId/edit'
import { ServerRoute as ApiAuthServerRouteImport } from './routes/api/auth'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc/$'

const rootServerRouteImport = createServerRootRoute()

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTimersRoute = publicTimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => publicRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardWeddingEventIdIndexRoute =
  authenticatedDashboardWeddingEventIdIndexRouteImport.update({
    id: '/dashboard/$weddingEventId/',
    path: '/dashboard/$weddingEventId/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardTimersTimerIdRouteRoute =
  authenticatedDashboardTimersTimerIdRouteRouteImport.update({
    id: '/dashboard/timers/$timerId',
    path: '/dashboard/timers/$timerId',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedDashboardTimersTimerIdEditRoute =
  authenticatedDashboardTimersTimerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => authenticatedDashboardTimersTimerIdRouteRoute,
  } as any)
const ApiAuthServerRoute = ApiAuthServerRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/timers': typeof publicTimersRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/dashboard/timers/$timerId': typeof authenticatedDashboardTimersTimerIdRouteRouteWithChildren
  '/dashboard/$weddingEventId': typeof authenticatedDashboardWeddingEventIdIndexRoute
  '/dashboard/timers/$timerId/edit': typeof authenticatedDashboardTimersTimerIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof publicRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/timers': typeof publicTimersRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/dashboard/timers/$timerId': typeof authenticatedDashboardTimersTimerIdRouteRouteWithChildren
  '/dashboard/$weddingEventId': typeof authenticatedDashboardWeddingEventIdIndexRoute
  '/dashboard/timers/$timerId/edit': typeof authenticatedDashboardTimersTimerIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(public)/timers': typeof publicTimersRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(authenticated)/dashboard/timers/$timerId': typeof authenticatedDashboardTimersTimerIdRouteRouteWithChildren
  '/(authenticated)/dashboard/$weddingEventId/': typeof authenticatedDashboardWeddingEventIdIndexRoute
  '/(authenticated)/dashboard/timers/$timerId/edit': typeof authenticatedDashboardTimersTimerIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/timers'
    | '/dashboard'
    | '/dashboard/timers/$timerId'
    | '/dashboard/$weddingEventId'
    | '/dashboard/timers/$timerId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/timers'
    | '/dashboard'
    | '/dashboard/timers/$timerId'
    | '/dashboard/$weddingEventId'
    | '/dashboard/timers/$timerId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(public)'
    | '/(auth-pages)/login'
    | '/(public)/timers'
    | '/(authenticated)/dashboard/'
    | '/(authenticated)/dashboard/timers/$timerId'
    | '/(authenticated)/dashboard/$weddingEventId/'
    | '/(authenticated)/dashboard/timers/$timerId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth': typeof ApiAuthServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth': typeof ApiAuthServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth': typeof ApiAuthServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth' | '/api/trpc/$'
  id: '__root__' | '/api/auth' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthServerRoute: typeof ApiAuthServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/timers': {
      id: '/(public)/timers'
      path: '/timers'
      fullPath: '/timers'
      preLoaderRoute: typeof publicTimersRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/$weddingEventId/': {
      id: '/(authenticated)/dashboard/$weddingEventId/'
      path: '/dashboard/$weddingEventId'
      fullPath: '/dashboard/$weddingEventId'
      preLoaderRoute: typeof authenticatedDashboardWeddingEventIdIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/timers/$timerId': {
      id: '/(authenticated)/dashboard/timers/$timerId'
      path: '/dashboard/timers/$timerId'
      fullPath: '/dashboard/timers/$timerId'
      preLoaderRoute: typeof authenticatedDashboardTimersTimerIdRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/dashboard/timers/$timerId/edit': {
      id: '/(authenticated)/dashboard/timers/$timerId/edit'
      path: '/edit'
      fullPath: '/dashboard/timers/$timerId/edit'
      preLoaderRoute: typeof authenticatedDashboardTimersTimerIdEditRouteImport
      parentRoute: typeof authenticatedDashboardTimersTimerIdRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardTimersTimerIdRouteRouteChildren {
  authenticatedDashboardTimersTimerIdEditRoute: typeof authenticatedDashboardTimersTimerIdEditRoute
}

const authenticatedDashboardTimersTimerIdRouteRouteChildren: authenticatedDashboardTimersTimerIdRouteRouteChildren =
  {
    authenticatedDashboardTimersTimerIdEditRoute:
      authenticatedDashboardTimersTimerIdEditRoute,
  }

const authenticatedDashboardTimersTimerIdRouteRouteWithChildren =
  authenticatedDashboardTimersTimerIdRouteRoute._addFileChildren(
    authenticatedDashboardTimersTimerIdRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardTimersTimerIdRouteRoute: typeof authenticatedDashboardTimersTimerIdRouteRouteWithChildren
  authenticatedDashboardWeddingEventIdIndexRoute: typeof authenticatedDashboardWeddingEventIdIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  authenticatedDashboardTimersTimerIdRouteRoute:
    authenticatedDashboardTimersTimerIdRouteRouteWithChildren,
  authenticatedDashboardWeddingEventIdIndexRoute:
    authenticatedDashboardWeddingEventIdIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicTimersRoute: typeof publicTimersRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicTimersRoute: publicTimersRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthServerRoute: ApiAuthServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
